### ISSUE TITLE
Crash when clear empty logs

### ISSUE THREAD

**Issue by brightsider** [JohnEstropia/JEToolkit#3]
In reloadLogEntriesForced bug:
if (shouldScrollToBottom) {
         [tableView
         scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:([self.displayedLogEntries count] - 1) inSection:0]
         atScrollPosition:UITableViewScrollPositionBottom
         animated:NO];
}
If self.displayedLogEntries contains 0 items app crashed.
Must be - if (shouldScrollToBottom && [self.displayedLogEntries count] > 0)

**Comment by JohnEstropia** [comment]
@brightsider Thanks for the report! I'll push the fix to 2.1.1 tag within the day
