### ISSUE TITLE
Cocoapods can't  import JEToolkit

### ISSUE THREAD

**Issue by hstdt** [JohnEstropia/JEToolkit#4]
It's a new swift project.

If  I install JEToolkit by Cocoapods, JEToolkit (JEDebugging or else)can not be found.

```
platform :ios, "8.0"

inhibit_all_warnings!
use_frameworks!


pod 'JEToolkit', '~> 3.0.0'
pod 'AFNetworking', '~> 3.0.4'
```

![image](https://cloud.githubusercontent.com/assets/10215098/11999502/930dfdd4-aafa-11e5-8922-82a85f5d84f7.png)

![image](https://cloud.githubusercontent.com/assets/10215098/11999523/fd638f28-aafa-11e5-8b24-02101ab559f5.png)

**Comment by JohnEstropia** [comment]
@hstdt Thanks for the report! I haven't prepared JEToolkit for framework-only projects yet, sorry. I'll push a fix as soon as I can.

**Comment by JohnEstropia** [comment]
@hstdt I forgot I already prepared a "module" branch for swift framework builds. Merged in the master branch now; tell me if there's any problem :)
