### ISSUE TITLE
Carthage can't build JEToolkit

### ISSUE THREAD

**Issue by sarukun99** [JohnEstropia/JEToolkit#6]
こんにちは、CarthageでJEToolkitを入れたいのですが、ビルドが進みません。
Carthage対応お願いできませんか？

環境は以下の通りです

```
Cartfile
github "JohnEstropia/JEToolkit"

bash-3.2$ Carthage version
0.11.0

bash-3.2$ xcodebuild -version
Xcode 7.2
Build version 7C68
```

宜しくお願いします！

**Comment by ainame** [comment]
carthage 0.12.0だと以下のメッセージが表示されました。

> Failed to discover shared schemes in project JEToolkitDemo.xcodeproj — either the project does not have any shared schemes, or xcodebuild timed out.

**Comment by JohnEstropia** [comment]
@sarukun99 @ainame 
連絡ありがとうございます！masterにschemeの追加をpushしましたので、試してみてください。
carthageのキャッシュを消してから `carthage update` でいけると思いますが、うまくいかなければ

```
github "JohnEstropia/JEToolkit" "3.0.3"
```

で実行するといいはずです！

**Comment by sarukun99** [comment]
できました！ありがとうございます。
