### ISSUE TITLE
It works not correctly at Xcode8 beta1

### ISSUE THREAD

**Issue by hstdt** [JohnEstropia/JEToolkit#9]
Same code between Xcode 7 and Xcode 8 beta 1.
Xcode7:
![image](https://cloud.githubusercontent.com/assets/10215098/16109747/015cee7e-33dd-11e6-9144-71c8872901db.png)

Xcode8:
![image](https://cloud.githubusercontent.com/assets/10215098/16109960/0bd548be-33de-11e6-8345-dcdf071053a5.png)

I'm not sure it is a bug of new Xcode.Thanks for your help.

**Comment by JohnEstropia** [comment]
Thanks for the report! I'll look into this.

**Comment by JohnEstropia** [comment]
What iOS version are you running this against? Does it work properly if you run XCode 8 with an iOS 9 device/simulator?

**Comment by JohnEstropia** [comment]
Looks like an iOS 10 bug. NSUserDefaults don't work properly even without using JEUserDefaults.

**Comment by hstdt** [comment]
@JohnEstropia 
Xcode8 - ios 9.3 simulator works properly(same as Xcode7 - ios 9.3)
Xcode8 - ios 10.0 simulator works incorrectly

**Comment by JohnEstropia** [comment]
This looks like a problem on iOS 10 (simulator) side so I'm closing this issue.
Do submit a [bug report to Apple](http://bugreport.apple.com) :)

**Comment by hstdt** [comment]
@JohnEstropia  It seems that we must enable keychain sharing in iOS 10 to access keychain.(Verified at Xcode8 beta6)
http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10/38799196#38799196

But the keychain data will **not** be copied to new keychain sharing group,is there a good idea to copy it? Thanks!

PS:
is it necessary to modify`#define USERINFO [[BSAUserInfo alloc]init]`to`
#define USERINFO [[BSAUserInfo alloc]initWithService:@"com.JEToolkit" accessGroup:NewKeychainSharingName]`?

**Comment by JohnEstropia** [comment]
@hstdt
Hi!
Is `BSAUserInfo` your `JEKeychain` subclass? If so, then yes that's how you'd do it.

**Comment by JohnEstropia** [comment]
@hstdt Have you tried enabling keychain access in Xcode **without** adding a keychain access group? I think your old code should work as it was.

**Comment by hstdt** [comment]
@JohnEstropia 
Thanks for your reply.

Enable keychain will automatic add a keychain group by Xcode.And I think keep it empty is not a good way to solve problem. 

Today I tried a few times by your advice (Xcode 7,Xcode 8, iOS9, iOS10),I find out that `accessGroup` be nil can work well sometimes.

If project need keychain sharing,and `JEKeychain` is designed as singleton,so we only need to find one way of access keychain at the beginning. I believe one of below will work...😁

![image](https://cloud.githubusercontent.com/assets/10215098/18262239/5a6db45e-7432-11e6-96dc-c932dffec5b4.png)

but wait for the stable Xcode version.
